---
driver:
  name: docker
  use_sudo: false
  socker: tcp://127.0.0.1:4243

provisioner:
  name: chef_zero

platforms:
  - name: debian

suites:
  - name: default
    run_list:
      - recipe[chef-ci-test::default]
    attributes:
