---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian

suites:
  - name: default
    run_list:
      - recipe[chef-ci-test::default]
    attributes:
